{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf500
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red1\green1\blue1;}
{\*\expandedcolortbl;;\cssrgb\c392\c392\c392;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl340\partightenfactor0

\f0\fs22\fsmilli11250 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 FROM python:alpine3.7\
COPY . /app\
WORKDIR /app\
RUN pip install -r requirements.txt\
CMD python ./index.py\
}